{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set build = 1 %}

# Higher number -> Always prioritize "novtk" variant over "all" variant
{% set build = build + 200 %}   # [variant == "novtk"]
{% set build = build + 100 %}   # [variant == "all"]

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  binary_relocation: false [osx]
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja >=1.10.2
    - cmake
    - swig >=4.0.2

  host:
    - python
    - boost-cpp
    - occt 7.7.2 *{{ variant }}*
    - libxml2
    - cgal-cpp
    - hdf5 1.12 # [win]
    - hdf5 # [not win]
    - mpfr
    - gmp  # [unix]
    - mpir  # [win]
    - nlohmann_json
    - zlib

  run:
    - python
    - occt 7.7.2 *{{ variant }}*
    - {{ pin_compatible('cgal-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
    - libxml2
    - mpfr
    - gmp  # [unix]
    - mpir  # [win]
    - nlohmann_json
    - zlib
  run_constrained:
    - occt 7.7.2 *{{ variant }}*

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell
