name: ci-blenderbim-daily

on:
  push:
    paths:
      - '.github/workflows/ci-blenderbim-matrix.yml'
      - 'src/blenderbim/**'
      - 'src/ifcopenshell-python/ifcopenshell/**'
      - 'src/bcf/src/bcf/**'
      - 'src/ifcclash/ifcclash/**'
      - 'src/ifccobie/**'
      - 'src/ifcdiff/**'
      - 'src/ifccsv/**'
      - 'src/ifcpatch/ifcpatch/**'
      - 'src/ifc4d/ifc4d/**'
      - 'src/ifc5d/ifc5d/**'
      - 'src/ifccityjson/**'
    branches:
      - v0.8.0
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
    - name: Set env
      run: echo ok go

  build:
    needs: activate
    name: ${{ matrix.config.name }}-${{ matrix.pyver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: [py39, py310, py311, py312]
        config:
          - {
            name: "Windows Build",
            short_name: win,
            blender_platform: windows-x64
          }
          - {
            name: "Linux Build",
            short_name: linux,
            blender_platform: linux-x64
          }
          - {
            name: "MacOS Build",
            short_name: macos,
            blender_platform: macos-x64
          }
          - {
            name: "MacOS ARM Build",
            short_name: macosm1,
            blender_platform: macos-arm64
          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          python-version: '3.11'
      - name: Get current version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Get current date
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Compile
        run: |
          cd src/blenderbim && make dist PLATFORM=${{ matrix.config.short_name }} PYVERSION=${{ matrix.pyver }}
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/blenderbim/dist/blenderbim_${{ matrix.pyver }}-${{steps.version.outputs.version}}-${{steps.date.outputs.date}}-${{ matrix.config.blender_platform }}.zip
          asset_name: blenderbim_${{ matrix.pyver }}-${{steps.version.outputs.version}}-${{steps.date.outputs.date}}-${{ matrix.config.blender_platform }}.zip
          release_name: "blenderbim-${{steps.version.outputs.version}}-${{steps.date.outputs.date}} (unstable)"
          tag: "blenderbim-${{steps.version.outputs.version}}.${{steps.date.outputs.date}}"
          overwrite: true
