name: ci-ifcopenshell-conda-daily

on:
  push:
      paths:
        - .github/workflows/ci-ifcopenshell-conda-daily.yml
        - conda/**
  schedule:
  #         ┌───────────── minute (0 - 59)
  #         │  ┌───────────── hour (0 - 23)
  #         │  │ ┌───────────── day of the month (1 - 31)
  #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         *  * * * *
  - cron: "49 23 * * *" # 11min before utc midnight every day

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'Krande/IfcOpenShell'
    steps:
      - name: Set env
        run: echo ok go

  test:
    name: ${{ matrix.platform.distver }}-${{ matrix.pyver.name }}-${{ matrix.variant }}
    needs: activate
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py311, distver: '3.11'},
          { name: py312, distver: '3.12'}
        ]
        platform: [
          { name: Windows, distver: windows-2022, upload: 'true' },
          { name: Linux, distver: ubuntu-22.04,  upload: 'true' },
          { name: macOS, distver: macos-12, upload: 'true' }
        ]
        variant: ['novtk', 'all']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download MacOSX SDK
        if: ${{ matrix.platform.name == 'macOS' }}
        run: |
          curl -o MacOSX10.13.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.13.sdk.tar.xz && \
          tar xf MacOSX10.13.sdk.tar.xz && \
          sudo mv -v MacOSX10.13.sdk /opt/ && \
          ls /opt/
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          cache-environment: true
          condarc: |
            channel_priority: strict
          create-args: >-
            python=3.11
            boa

      - name: build, test and upload ifcopenshell
        if: ${{ matrix.platform.upload == 'true' }}
        run: |
          conda-build . --python ${{ matrix.pyver.distver }} -c conda-forge --variants "{variant: ${{ matrix.variant }}}"
        working-directory: ./conda
